FORMAT: 1A
HOST: https://api-test.enterprise.agero.com/OEM/V1

# OEM Roadside Assistance API
Roadsides Assistance service allows the clients to secure roadside assistance service by providing a minimal set of required information. On request being initiated in the backend, the system dispatches a service provider and sends out a closed loop notification.

Clients can do the following operations:

- Submit a request for Roadside Assistance
- Query the status of an already submitted Roadside Assistance request.

![WorkFlow](https://apiportal.agero.com/sites/default/files/OEM_Workflow.jpg)

##Getting Started

This section describes the basic knowledge that readers should possess before beginning to develop using the API.

##URI Structure

https://host:port/context/v/path

host and port define the host and port where the application lives.

context is the context of the application, in this case the “RSA/OEM”.

v is the API version

path is the path declared in the REST interface.

For our example, in order to request a Roadside Assistance door unlock, client would construct

the URI as follows:

HTTPS://API.AGERO.COM:80/OEM/VX.X/RSA

The Base URI is defined to be all parts of the URI up to and including version component (HTTPS://API.AGERO.COM:80/OEM/VX.X/). The Base URI will be communicated to clients of the API who then can use it as prefix to the paths defined for each API operation.
HTTP-based

Methods to retrieve data from the API require a GET request. Methods that submit – or create new data – require a POST. Methods that change data require a PUT. Methods that destroy data require a DELETE. Requests to the API that require a particular HTTP method will return an error if the request contains the incorrect method. The POST and PUT verbs are used in requests that have an HTTP body and the request data is housed in the HTTP request body. The GET and DELETE verbs are used in conjunction with requests that have no body. The request data is sent as query strings. Requests that use PUT and DELETE are idempotent. This means that no matter how many times the methods are invoked, the resource state on the server is only changed once.
##What is an Application Key?

Application Key is a client specific component which is used to route requests to the correct instance/implementation of the API. The actual value of this component is decided individually for each client by Agero.
##How to procure an Application Key?

To develop applications using the API, client must request for Agero to create a unique application key in the back-end system to support the application. The result is that Agero provides, for your application, a unique application key.

The application key is an important piece of data. It should not be used by more than one application nor should it be given to other developers.

# Group Submit RSA Request

###Description

Used to submit a Roadside Assistance request. Client is required to submit a set of mandatory data elements to successful submission.

###Extended Header Parameters
   
    x-apiKey
    
###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request
    HTTP 401 : Unauthorized
    HTTP 403 : Forbidden
    HTTP 404 : Not Found
    HTTP 405 : Not Allowed
    HTTP 500 : Internal Server Error
    HTTP 501 : Service Unavailable    
    
###Request Body Schema

![Request Body Schema](https://apiportal.agero.com/sites/default/files/INS_SRRequestBody.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|requestor   | Encapsulates the callers information  |Caller |   Y   | | Refer to the Requestor section for further details | 
|disablement Location|Encapsulates the disablement location of the vehicle |DisablementLocation|Y||  Refer to the Disablement Location section for further details |                                                                                                             
|notification Preferences|Encapsulates the details & preference mode of how the user wants to be notified of the service updates|NotificationPreferences|Y||Refer to the Notification Preferences section for further details|                                                      Preferences section for |notified of the service updates                                                       further details|
|towDestination|Encapsulates the tow destination mode of how the user wants to be knows where the vehicle needs to be towed to|TowDestination|N||Refer to the Tow Destination section for further details|
|vehicle|Encapsulates the details of the vehicle which needs roadside assistance|Vehicle|Y||Refer to the Vehicle section for further details|
|serviceDetails| Encapsulates the details of the roadside| ServiceDetails|Y||Refer to the ServiceDetails section for further details|
  
 
#####Requestor

![Requestor](https://apiportal.agero.com/sites/default/files/INS_Requestor.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|name   | Name of the Caller  |Name |   Y   | | Please refer to Name section for further details. | 
|callbackNumber|PhoneNumber the caller can be reached at if call centre rep needs to get in touch with caller regarding the case|String|Y|781-306-3562|  Format: xxx-xxx-xxxx This also serves as a reference# if customer needs to call the call centre rep


#####name

![name](https://apiportal.agero.com/sites/default/files/INS_Name.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|firstName   | First name of the caller  |String |   Y   |Tommy | Max Length:50  No special characters| 
|lastName   | Last name of the caller  |String |   Y   |Decourcy | Max Length:50  No special characters| 
|middleInitial   | Middle Initial of the caller  |String |   Y   | | Max Length:50  No special characters| 


 
#####Disablement Location

![Disablement Location](https://apiportal.agero.com/sites/default/files/INS_DisablementLocation.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|address   | Encapsulates the address of the disablement  |Address |   Y   | |If provided, takes precedence over geographical Coordinates| 
|geographical Coordinates   |   |geographical Coordinates |   Y   | | | 


#####Tow Destination

![Tow Destination](https://apiportal.agero.com/sites/default/files/INS_TowDestination.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|address   | Encapsulates the address of the disablement  |Address |   N   | |If provided, takes precedence over geographical Coordinates| 
|geographical Coordinates   | GPS coordinates of the tow destination address   |geographical Coordinates |   Y   | Home|Please refer to Geographical Coordinates section for further details   | 
|destinationBusinessName   |Business name of destination where the vehicle needs to be towed to  |String |   N   |PEPBOYS-Everett |Max Length:50 No special characters| 
|destinationType   | Type of the destination   |String numeration|   Y   | Repair Facility |Possible Values (Case Sensitive): Dealership Repair Facility  Other | 


#####Address

![Address](https://apiportal.agero.com/sites/default/files/INS_Address.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|city   |  |String |   Y   | Boston |Max Length:50 No special characters| 
|country   |  |String |   Y   | USA |Possible Values: No special characters |
|state   |  |String |   Y   | MA |Max Length:50 No special characters| 
|streetAddress1   |  |String |   Y   | 9 High Street |Max Length:50 No special characters| 
|streetAddress2   |  |String |   Y   | Apt B |Max Length:50 No special characters| 
|zip   |  |String |   Y   | 02115  || 
   
    
#####Geographical Coordinates

![Geographical Coordinates](https://apiportal.agero.com/sites/default/files/INS_geographocalCoordnates.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|longitude   |  Longitude coordinate |Double |   Y   | -122.030725 |
|latitude   | Latitude Coordinate  |Double |   Y   | 37.33174  |

  
    
#####Notification Preferences

![Notification Preferences](https://apiportal.agero.com/sites/default/files/INS_NotificationPreferences.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|preferred Mode   |  Preferred mode for closed loop notification |String |   Y   | Email |Possible Values(Case Sensitive):SMS VoiceCall Email   |
|emailId   | Email address of the customer where email notification is to be sent |String |   Y/N  | sjohn@agero.com |Required if Preferred Mode is Email. Optional otherwise|
|textMessageNumber   | Phone# of the customer where SMS notification is to be sent |String |   Y/N   | 781-306-1234 |Required if Preferred Mode is SMS. Optional otherwise. Format: xxx-xxx-xxxx  |
|primaryPhoneNumber   | Phone# of the customer where the customer needs to be called for notification updates  |String |  Y/N  | 781-306-1234 |Required if Preferred Mode is VoiceCall.Optional otherwise. Format: xxx-xxx-xxxx|

                            
#####Vehicle

![Notification Preferences](https://apiportal.agero.com/sites/default/files/INS_Vehicle.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|vin   |  Vehicle Identification number of the Vehicle   |String |   Y   |  |17 chars No special characters allowed   |
|mileage   |  Mileage on Odometer of vehicle   |Integer |   N   | 14532 |NNNNN format NNNNN format  |
|year   |  Year built   |String |   N   | 2012 |YYYY format.Y- numeric digit   |
|make   |     |String |   N    |  | Max Length:50  No special characters allowed   |
|model   |    |String |   N    |  |Max Length:50  No special characters allowed    |
|color   |  Color of vehicle   |String |   N    |  Blue |Max Length:50  No special characters allowed    |
|licensePlate   |  Plate # of Vehicle   |String |   N    | 198NP4|Max Length:50  No special characters allowed    |
|fuelType   |  FuelType of the vehicle    |String |   N    | HKJ656568GJGJH|This is helpful if the user is requesting Roadside Assistance for “Out of Fuel” disablement reason.Possible Values (Case Sensitive):Gasoline Diesel|



#####ServiceDetails

![ServiceDetails](https://apiportal.agero.com/sites/default/files/INS_ServiceDetails.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|disablementReason   |   Type of Roadside Assistance being requested  |String Enumeration |   Y   | Multiple Flat Tire  |Possible Values(Case Sensitive): Lockout – Keys in car Out of Fuel.... Please refer to Disablement Reason Descriptions for detailed description of disablement reasons and when they need to be used. |
|comments   |  Additional comments that need to be associated with the  Roadside Assistance request. |Array of Comment |   N   | Two Flat Tires |  |


    
#####Response Body Schema

![Response Body Schema](https://apiportal.agero.com/sites/default/files/INS_SRResponseBody.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|rsaRequestId   |  Confirmation# for the request submitted |String|   Y   | HKJ656568GJGJH |  |


  
## Submit RSA Request [/RSA]
### Submit RSA Request [POST]

+ Request (application/json)

    + Header

            x-apiKey: VUWZhJFOlgPscAYGWafXFoansPVnHSYw
            Accept: application/json
            
    + Body
    
            {
               "requestor":{
                  "name":{
                     "firstName":"Tom",
                     "lastName":"Decourcy",
                     "middleInitial":"C"
                  },
                  "callbackNumber":"781-306-1234"
               },
               "disablementLocation":{
                  "address":{
                     "streetAddress1":"67 Georgetown Dr",
                     "streetAddress2":"",
                     "city":"Framingham",
                     "state":"MA",
                     "country":"USA",
                     "zip":"01702"
                  },
                  "geographicalCoordinates":{
                     "latitude":37.33174,
                     "longitude":-122.030725
                  }
               },
               "towDestination":{
                  "destinationBusinessName":"Firestone Complete Auto Care",
                  "destinationType":"Repair Facility",
                  "address":{
                     "streetAddress1":"1450 Worcester Rd",
                     "streetAddress2":"",
                     "city":"Framingham",
                     "state":"MA",
                     "country":"USA",
                     "zip":"01702"
                  },
                  "geographicalCoordinates":{
                     "latitude":37.33174,
                     "longitude":-122.030725
                  }
               },
               "vehicle":{
                  "make":"Lincoln",
                  "model":"MKS",
                  "year":2012,
                  "licensePlate":"81ZP67",
                  "mileage":"12000",
                  "vin":"SFJKHGS76926424JH",
                  "color":"Red",
                  "fuelType":"Gasoline"
               },
               "notificationPreferences":{
                  "preferredMode":"email",
                  "emailId":"tdecourcy@agero.com",
                  "textMessageNumber":null,
                  "primaryPhoneNumber":null
               },
               "serviceDetails":{
                  "disablementReason":" Lockout - Keys in car ",
                  "comments":[{"value":"2 tires are flat"},{"value":"Please send help    soon"}]   }
            }
                        
     
    
+ Response 200 (application/json)

    + Body

            {
            
                "rsaRequestId":"7537adf9-7187-4561-8c43-d1149901308b"
            
            }

# Group Get RSA Request Status

###Description

Used for retrieving current status of an already created RSA request.

###Extended Header Parameters
   
    x-apiKey
    
###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request
    HTTP 401 : Unauthorized
    HTTP 403 : Forbidden
    HTTP 404 : Not Found
    HTTP 405 : Not Allowed
    HTTP 500 : Internal Server Error
    HTTP 501 : Service Unavailable    
    
###Sample Request

#####Header

GET BaseURI/RSA/7537adf9-7187-4561-8c43-d1149901308b HTTP 1.1

x-apiKey: VUWZhJFOlgPscAYGWafXFoansPVnHSYw

#####Body

n/a

###Sample Response

#####Header
HTTP/1.1 400 Ok

Content-Type: application/json;charset=UTF-8

#####Body
{

  "rsaRequestStatus":"IN PROGRESS",

  "link":

  {
   
   "rel":"",

   "href":"http://roadsideconnect.com/?id=781-306-1234",
 
  }
  
}

###Response Body Schema 

![Response Body Schema](https://apiportal.agero.com/sites/default/files/INS_GRReuestbody.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|rsaRequestStatus   |Status of the request |String Enumeration |   Y   | IN PROGRESS | Possible Values:REQUEST CONFIRMED IN PROGRESS SERVICE PROVIDER DISPATCHED SERVICE COMPLETE | 
|link  |Provides the URL for Roadside Connect application which provides up to minute information on the progression of request |Link |   N  |

                                                                                                 
                
#####link

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|rel  |Status of the request |String Enumeration |   Y   | IN PROGRESS | 
|href   |Provides the URL for Roadside Connect application which Connect application which provides up to minute information on the progression of request |URI |   Y  |


#####Error Response
|  |  |
|:-------------|:-----------------|
|Description|Error response is returned if the request if the request data is not compliant with expected schema such as missing required data elements OR if invalid valuespassed for data elements.|
|Sample Request||
|Header|HTTP/1.1 400 Ok Content-Type: application/json;charset=UTF-8|
|Body | {"error":{"message":"The email address supplied is invalid","code":"InvalidEmailId"}}|
    
    
#####Response Body Schema

![Link](https://apiportal.agero.com/sites/default/files/INS_Link.jpg)

| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|code   | Error identifier code |String |   Y   | InvalidEmailId | 
|message    |Descriptive message of the root cause of the error   |String |   Y  | The email address supplied is invalid |


                        
## Get RSA Request Status [/RSA/1048700144]

+ parameter 

    + rsaRequestId(required, string) ... The confirmation Id returned for the RSA request submitted.
    
### Get RSA Request Status [GET]

+ Request   ()

    + Header
     
            x-apiKey: VUWZhJFOlgPscAYGWafXFoansPVnHSYw
            Accept: application/json
    
+ Response 200 (application/json)

    + Body
            
            {
              "rsaRequestStatus":"IN PROGRESS",
              "link":
              {
               "rel":"",
               "href":"http://roadsideconnect.com/?id=781-306-1234",
              }
            }

# Group Error Response

###Description
Error response is returned if the request if the request data is not compliant with expected schema such as missing required data elements OR if invalid values passed for data elements.

###Sample Response
HTTP/1.1 404 Ok
Content-Type:   application/json;charset=UTF-8

{"error":{"message":"The email address supplied is invalid","code":"InvalidEmailId"}}


###Response Body Schema 

![Response Body Schema ](https://apiportal.agero.com/sites/default/files/INS_ErrorResonseBody.jpg)


| Data Element | Description | Data Type  | Mandatory (Y/ N) | Value/Example | Note |
|:-------------|:------------|:-----------|:-----------------|:--------------|:-----|
|code  |Error identifier code |String |   Y   | InvalidEmailId | |
|message  |Descriptive message of the root cause of the error |String |   Y   | The email address supplied is invalid | |  

###Disablement Reason Descriptions

| |   |    | 
|:-----|:--------------------|:--------------|
|1| Lockout - Keys in car |This call reason should be selected by the customer when they can access their vehicle key upon the Service Provider unlocking the driver's side door.  For example, when customer left their key(s) in the cup holder, or on the passenger’s seat. If the user left their key(s) in the trunk and the trunk is not accessible after the driver's door is unlocked then this option should not be used.|
|2|Lockout - Keys broken/missing |This call reason should be selected by the customer when the vehicle key is missing or broken. Sometimesaccessing the vehicle requires the Service Provider to take the customer to the Dealership for further assistance. For this scenario, the customer will need to speak with an Agero Call Center Representative to further define the level of| 
|3| Vehicle Stuck|This call reason requires the customer to speak with an Agero Call Center Representative to further define the situation.There are different service levels associated with a vehicle being stuck in the mud, snow, or ditch.  The Service Provider will need to know what type of equipment to bring to the disablement location.| 
|4|Out of Fuel (Cost of fuel not covered)|This call reason requires the customer to speak with an Agero Call Center epresentative to determine the type of fuel required.  The Service Provider cannot solely go by VIN VIN to determine what type of fuel to bring (e.g.  Gasoline, Diesel, Hybrid,Hybrid-Electric, Flexible, Methanol/Ethanol etc..)| 
|5|Accident/Vandalism|This call reason requires the customer to speak with an Agero Call Center Representative to access damage and perform follow-up calls to the customer's insurance carrier for coverage.|
|6|One Flat Tire – Good spare|The customer will select this option when they have one flat tire, a good spare, and when the vehicle does not have any body damage.The flat tire should not be the result of an accident or act of vandalism.|
|7|Multiple Flat Tires| This call reason requires the customer to speak with an Agero Call Center Representative|to determine if there is a good spare tire and if there has been any damage to the tire rim. If there are three or more flat tires then the customer may have to secure the new tires before the vehicle can be serviced.|
|8|Tow  (Not leaking fuel)|The customer should select this reason if they cannot start the vehicle and have attempted a jump start.   There may be various reasons for the customer to select this reason such  as the vehicle is overheating; an electrical/mechanical problem,and/or the brakes are not working.If the vehicle is leaking fuel, has just been in an accident, or vandalized then the customer should contact the Agero Call Center immediately.|  
|9|Jump Start (Did not stall while driving)| The customer will select this reason if they have not attempted a jump start and the vehicle never started or stalled when driving.  When the customer selects this reason the Service Provider will arrive at the Disablement Location with a jump start.If the customer has already attempted a jump start then they should select the 'Tow' option in the event there is an issue with their alternator.| 
|10|Unknown Problem|This call reason requires the customer to speak with an Agero Call Center Representative to etermine the type of service they require.| 
